name: 🐛 Bug Report
description: File a bug report
title: "[🐞]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: os
    attributes:
      label: What OS are you seeing the problem on?
      multiple: false
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: false
  - type: dropdown
    id: psversion
    attributes:
      label: What OS are you seeing the problem on?
      multiple: true
      options:
        - Windows PowerShell 5.1
        - PowerShell 7
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please enter an explicit description of your issue
      placeholder: Short and explicit description of your incident...
    validations:
      required: true
