name: 💡 Feature Request
description: Open a feature request
title: "[💡]: "
labels:
  - enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please enter an explicit description of your feature request
      placeholder: Detailed and explicit description of your request...
    validations:
      required: true
